var mongoose = require('mongoose');
//Schema
var VendorInfoSchema = new mongoose.Schema({
    id:String,
	username:String,
    email: String,
    logo:String,
    name:String,
    uniqueid:String,
    isOpen:Number,
    phone:Number,
    scope:Number,
    community:[{name:String}],
    address:{addressLine1:String,
        addressLine2:String,
        street:String, 
        LandMark:String, 
        areaName:String,
        city:String, 
        zip:String, 
        latitude:Number,
        longitude:Number },
    profiles:[{  id:String,
                phone:Number,
                name:String,
                email: String,
                dob:String,
                age:Number,
                gender:String,
                community:String,
                occupation:String,
                education:String,
                logo:String,
                profileLogo:String,
                summary:String,
                otherDetails:String,
                interests:String,
                mothertongue:String,
                income:Number,
                gothra:String,
                star:String,
                rashi:String,
                height:Number,
                weight:Number,
                father:{name:String,occupation:String,phone:String},
                mother:{name:String,occupation:String,phone:String},
                address:{label:String, 
                    addressLine1:String,
                    addressLine2:String,
                    street:String, 
                    LandMark:String, 
                    areaName:String,
                    city:String, 
                    zip:String, 
                    latitude:Number,
                    longitude:Number },
                maritalstatus:String,
                complexion:String,
                state:String,
                native:String,
                castdetails:String,
                padha:String,
                lagna:String,
                gothradetails:String,
                homegod:String,
                religionotherdetails:String,
                educationdetails:String,
                occupationdetails:String,
                joblocation:String,
                brotherdetails:String,
                sisterdetails:String,
                birthplace:String,
                horoscope:[String]
                }]
    }); 

//Model
var VendorInfoModel = mongoose.model( 'VendorInfoSchema', VendorInfoSchema );

module.exports = VendorInfoModel;